apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketboard-frontend
  namespace: ticketboard
  labels:
    app: ticketboard-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketboard-frontend
  template:
    metadata:
      labels:
        app: ticketboard-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/ghostgto/ticketboard-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://ticketboard-backend.ticketboard.svc.cluster.local:3000"
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
