apiVersion: v1
kind: Service
metadata:
  name: ticketboard-frontend
  namespace: ticketboard
spec:
  selector:
    app: ticketboard-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
